### ISSUE TITLE
Gallery version

### ISSUE THREAD

**Issue by cornae** [euphorie/osha.oira#23] opened 2015-04-24 21:49 UTC
Could someone check what version we use of the javascript behind pat-gallery? We use it also for Star White side and there we upgraded (or at least also needed to upgrade) to a newer version of the script that doesn't feature this unwanted page reload after you close the gallery.

**Comment by cornae** [comment] 2015-05-02 18:10
@pysailor, Can I get some follow up on this one?

**Comment by pysailor** [comment] 2015-05-03 13:40
@jcbrand Do you have enough info to answer? With the rewriting of history I can't say what was done for pat-gallery in the last months (https://github.com/Patternslib/Patterns/blob/master/src/pat/gallery/gallery.js)

**Comment by pilz** [comment] 2015-05-04 06:40
We use src/legacy/photoswipe.js version 3.0.5.1. There is currently a version 4.0.7 at http://photoswipe.com.

**Comment by jcbrand** [comment] 2015-05-04 07:36
@pysailor: The history for pat-gallery should still be there and in full. If a file was moved, you need to add ``--follow`` when you call `git log`.

**Comment by jcbrand** [comment] 2015-05-19 13:08
I checked and the star version of Photoswipe is exactly the same version used in Patternslib. I don't know why @cornae thinks that we have a newer version there. Perhaps there was a regresssion?

**Comment by jcbrand** [comment] 2015-05-19 13:09
Ah, I see now that you say "or at least also needed to upgrade".

**Comment by cornae** [comment] 2015-05-19 14:53
We’ve been looking at the upgrade and we planned to do it. I didn’t know if that ever happened, but I assumed it did happen :). The upgrade is vital for Star White side too since it also uses injection and therefor we don’t want a page refresh.

**Comment by jcbrand** [comment] 2015-05-20 15:35
@cornae: This is fixed now and available in the newest bundle in the proto.

After updating to the newest Photoswipe, we lost 2 configuration arguments because they're not available in the newest version (which was rewritten from scratch).

These are the ``slideshow``, ``effect-duration``, ``effect-easing`` and ``hide-overlay`` arguments.

The new Photoswipe library doesn't support changing images automatically in a slideshow, which is why I removed the ``slideshow`` argument. I hope this is not too much of a regression :(

On related note, what is the intended difference between `pat-slides` and `pat-gallery`?

**Closed** 2015-09-23 15:57 UTC
